#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zap"
name = "Zap"
description.en = "Ethical fediverse server alternative"
description.fr = "serveur fedverse éthique"

version = "21.11.28~ynh3"

maintainers = []

[upstream]
license = "MIT"
code = "https://codeberg.org/zot-archive/zap"
website = "https://codeberg.org/zot-archive/zap"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://codeberg.org/zot-archive/zap/archive/078714b9dde991d02f8cce1183ce357d96405558.tar.gz"
    sha256 = "6159da945fe504bffe23f80d299bfe3e146a9d9df76412f5bea6d1d415516d34"

    [resources.sources.app_addons]
    url = "https://codeberg.org/zot-archive/zap-addons/archive/b2ddcc67735fb413f14efcc9c49780469b8b61cf.tar.gz"
    sha256 = "009f5047096fdbe3becaebfb7ac3ee34d7efd3f4f891e3a645484a7e406598a1"
    in_subdir = false


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "postgresql",
        "postgresql-contrib",
        "php7.4-pgsql",
        "php7.4-mbstring",
        "php7.4-cli",
        "php7.4-imagick",
        "php7.4-xml",
        "php7.4-zip",
        "php7.4-json",
        "php7.4-gd",
    ]

    [resources.database]
    type = "postgresql"
