test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.database = "mysql"

[postgresql_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.database = "postgresql"
