#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_remove_nginx_config

# Remove the dedicated php-fpm config
ynh_remove_fpm_config

# Remove the app-specific logrotate config
ynh_remove_logrotate

# Remove a cron file
ynh_secure_remove --file="/etc/cron.d/$app"

ynh_remove_fail2ban_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
