#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..."

ynh_restore_file --origin_path="$install_dir"

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================
#REMOVEME? ynh_script_progression --message="Restoring the MySQL database..."

if [  $database -eq 1 ]; then
#REMOVEME? 	ynh_script_progression --message="Restoring  MySQL database..."
#REMOVEME? 	db_pwd=$(ynh_app_setting_get --app=$app --key=mysqlpwd)
#REMOVEME? 	ynh_mysql_setup_db --db_user=$db_name --db_name=$db_name --db_pwd=$db_pwd
	ynh_mysql_connect_as --user=$db_name --password=$db_pwd --database=$db_name < ./db.sql
elif [ $database -eq 2 ]; then
	# Removing postgresql database
#REMOVEME? 	ynh_script_progression --message="Reinstalling dependencies..."
	# Define and install dependencies
#REMOVEME? 	ynh_install_app_dependencies $pkg_dependencies
#REMOVEME? 	ynh_script_progression --message="Restoring the PostgreSQL database..."
#REMOVEME? 	db_pwd=$(ynh_app_setting_get --app=$app --key=psqlpwd)
#REMOVEME? 	ynh_psql_test_if_first_run
#REMOVEME? 	ynh_psql_setup_db --db_user=$db_user --db_name=$db_name --db_pwd=$db_pwd
	ynh_psql_execute_file_as_root --file="./db.sql" --database="$db_name"
fi

#=================================================
# RESTORE THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring PHP-FPM configuration..."

ynh_restore_file --origin_path="/etc/php/$phpversion/fpm/pool.d/$app.conf"

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore_file --origin_path="/etc/cron.d/$app"

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

ynh_restore_file "/etc/fail2ban/jail.d/$app.conf"
ynh_restore_file "/etc/fail2ban/filter.d/$app.conf"
ynh_systemd_action --action=restart --service_name=fail2ban

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression --message="Reloading NGINX web server and PHP-FPM..."

ynh_systemd_action --service_name=php$phpversion-fpm --action=reload
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app"
